/* ====================================================================
 * HUTB Campus Guide - Data Layer
 * 湖南工商大学（北校区）生活指南
 * 数据存储：localStorage
 * ==================================================================== */
(function(global){'use strict';
const STORAGE_PREFIX='hutb_campus_';
const VERSION_KEY=STORAGE_PREFIX+'version';
const CURRENT_VERSION='1.1.0';

/* 默认食堂数据 */
const DEFAULT_FOOD=[
{id:'food_001',title:'铭德食堂 · 常德米粉',category:'校内食堂',cover:null,
excerpt:'一食堂主打湖南常德风味，强烈推荐西红柿鸡蛋拌面和蛋炒粉。',
content:'<p>铭德食堂一楼，常德米粉窗口。招牌西红柿鸡蛋拌面 10 元，蛋炒粉 8 元，稍贵但味道好。还有老长沙米粉（有肠粉）。</p><h4>推荐菜品</h4><ul><li>西红柿鸡蛋拌面</li><li>蛋炒粉</li><li>常德牛肉粉</li><li>老长沙肠粉</li></ul><h4>营业时间</h4><p>早餐 6:30-9:00 ｜ 午餐 11:00-13:30 ｜ 晚餐 17:00-19:30</p>',
tags:['湖南米粉','面食','一食堂'],location:'湖南工商大学北校区·铭德食堂（一食堂）1楼',
recommendedDishes:['西红柿鸡蛋拌面','蛋炒粉','常德牛肉粉'],priceRange:'¥8-12',rating:4.6,
pinned:true,sortOrder:1,published:true,createdAt:'2026-08-01T08:00:00Z',updatedAt:'2026-08-10T08:00:00Z'},
{id:'food_002',title:'铭德食堂 · 盖世英雄',category:'校内食堂',cover:null,
excerpt:'一食堂饭菜类档口，份量足，堂食不能分装。',
content:'<p>铭德食堂二楼，盖世英雄档口，专注做各类炒菜套餐。份量足，味道家常。注意：堂食不支持分装打包，需在窗口说明。</p><h4>推荐菜品</h4><ul><li>糖醋排骨套餐</li><li>红烧肉套餐</li><li>农家小炒肉</li></ul>',
tags:['套餐','炒菜','堂食'],location:'湖南工商大学北校区·铭德食堂（一食堂）2楼',
recommendedDishes:['糖醋排骨套餐','红烧肉套餐'],priceRange:'¥12-18',rating:4.3,
pinned:false,sortOrder:2,published:true,createdAt:'2026-08-01T08:00:00Z',updatedAt:'2026-08-05T08:00:00Z'},
{id:'food_003',title:'铭德食堂 · 大内香酥鸭',category:'校内食堂',cover:null,
excerpt:'便宜量大，适合干饭人。',
content:'<p>铭德食堂内性价比之选，份量足、价格低，适合饭量大的同学。</p><h4>推荐菜品</h4><ul><li>香酥鸭套餐</li><li>卤肉饭</li></ul>',
tags:['便宜','量大','快餐'],location:'湖南工商大学北校区·铭德食堂（一食堂）',
recommendedDishes:['香酥鸭套餐','卤肉饭'],priceRange:'¥8-14',rating:4.2,
pinned:false,sortOrder:3,published:true,createdAt:'2026-08-01T08:00:00Z',updatedAt:'2026-08-04T08:00:00Z'},
{id:'food_004',title:'二食堂 · 匠心卤',category:'校内食堂',cover:null,
excerpt:'清淡口味，椒麻肉丝饭可双拼三拼，灵活搭配。',
content:'<p>二食堂一楼，匠心卤档口，口味清淡。招牌椒麻肉丝饭 12 元、椒麻鸡丝饭 11 元，可双拼或三拼。</p><h4>推荐菜品</h4><ul><li>椒麻肉丝饭</li><li>椒麻鸡丝饭</li><li>卤味拼盘</li></ul><h4>提醒</h4><p>自选窗口偏贵，别选压称的。</p>',
tags:['卤味','清淡','双拼'],location:'湖南工商大学北校区·二食堂1楼',
recommendedDishes:['椒麻肉丝饭','椒麻鸡丝饭'],priceRange:'¥10-15',rating:4.5,
pinned:true,sortOrder:4,published:true,createdAt:'2026-08-01T08:00:00Z',updatedAt:'2026-08-06T08:00:00Z'},
{id:'food_005',title:'二食堂 · 渔粉/花甲粉/螺蛳粉',category:'校内食堂',cover:null,
excerpt:'二食堂汤粉系列，花甲粉鲜，螺蛳粉够劲。',
content:'<p>二食堂渔粉档口，主打各类汤粉。</p><h4>推荐菜品</h4><ul><li>渔粉（招牌）</li><li>花甲粉（鲜）</li><li>螺蛳粉（够劲）</li><li>热干面</li></ul>',
tags:['汤粉','粉类','二食堂'],location:'湖南工商大学北校区·二食堂',
recommendedDishes:['渔粉','花甲粉','螺蛳粉'],priceRange:'¥10-14',rating:4.4,
pinned:false,sortOrder:5,published:true,createdAt:'2026-08-01T08:00:00Z',updatedAt:'2026-08-06T08:00:00Z'},
{id:'food_006',title:'后街 · 十二元砂锅粉自选',category:'周边小吃',cover:null,
excerpt:'好吃实惠，配菜自选，后街性价比之王。',
content:'<p>后街人气摊位，十二元一份，荤素自选配菜。强烈推荐加一份肉丸或卤蛋。</p><h4>推荐理由</h4><ul><li>便宜：¥12 管饱</li><li>自选：配菜灵活</li><li>好吃：一致好评</li></ul>',
tags:['便宜','自选','后街'],location:'湖南工商大学北校区后街',
recommendedDishes:['砂锅粉','加卤蛋','加肉丸'],priceRange:'¥12-16',rating:4.7,
pinned:true,sortOrder:6,published:true,createdAt:'2026-08-01T08:00:00Z',updatedAt:'2026-08-08T08:00:00Z'},
{id:'food_007',title:'后街 · 土豆泥拌面',category:'周边小吃',cover:null,
excerpt:'口味独特，土豆泥裹满面条。最近分量略少，胃口小的刚好。',
content:'<p>后街特色小吃，土豆泥拌面 8-10 元，口味独特，咸香浓郁。最近有同学反映分量比之前少，建议胃口大的额外加份。</p>',
tags:['面食','特色','后街'],location:'湖南工商大学北校区后街',
recommendedDishes:['土豆泥拌面'],priceRange:'¥8-12',rating:4.3,
pinned:false,sortOrder:7,published:true,createdAt:'2026-08-01T08:00:00Z',updatedAt:'2026-08-08T08:00:00Z'},
{id:'food_008',title:'后街 · 猪油炒饭',category:'周边小吃',cover:null,
excerpt:'后街最好吃的炒饭！熊二炒饭排第二，其他都不行。',
content:'<p>后街炒饭摊，猪油炒饭 10 元，据同学们一致评价是后街最好吃的炒饭。熊二炒饭次之，其余炒饭均不推荐。</p>',
tags:['炒饭','后街','必吃'],location:'湖南工商大学北校区后街',
recommendedDishes:['猪油炒饭','熊二炒饭'],priceRange:'¥10-12',rating:4.8,
pinned:true,sortOrder:8,published:true,createdAt:'2026-08-01T08:00:00Z',updatedAt:'2026-08-08T08:00:00Z'},
{id:'food_009',title:'后街 · 旋记鸭霸王',category:'周边小吃',cover:null,
excerpt:'吃辣必试！辣得过瘾，回味无穷。',
content:'<p>后街卤味摊，主打鸭霸王系列产品，能吃辣的直接冲。</p>',
tags:['卤味','辣','后街'],location:'湖南工商大学北校区后街',
recommendedDishes:['鸭霸王','麻辣鸭脖'],priceRange:'¥8-15',rating:4.5,
pinned:false,sortOrder:9,published:true,createdAt:'2026-08-01T08:00:00Z',updatedAt:'2026-08-08T08:00:00Z'},
{id:'food_010',title:'后街 · 后街炸鸡',category:'周边小吃',cover:null,
excerpt:'干干脆脆，一致好评，吃过都说好。',
content:'<p>后街炸鸡摊位，外酥里嫩，干干脆脆的口感在学生中口碑极佳。</p>',
tags:['炸鸡','后街','零食'],location:'湖南工商大学北校区后街',
recommendedDishes:['炸鸡腿','炸鸡排'],priceRange:'¥8-15',rating:4.6,
pinned:false,sortOrder:10,published:true,createdAt:'2026-08-01T08:00:00Z',updatedAt:'2026-08-08T08:00:00Z'},
{id:'food_011',title:'后街 · 肉夹馍',category:'周边小吃',cover:null,
excerpt:'味道好，但分量偏少，胃口大的可能吃不饱。',
content:'<p>后街肉夹馍摊，味道不错但每份分量偏少，建议多买一个或搭配其他食品。</p>',
tags:['面食','后街','轻量'],location:'湖南工商大学北校区后街',
recommendedDishes:['卤肉夹馍'],priceRange:'¥6-10',rating:4.2,
pinned:false,sortOrder:11,published:true,createdAt:'2026-08-01T08:00:00Z',updatedAt:'2026-08-08T08:00:00Z'},
{id:'food_012',title:'后街 · 煎饼（阿姨摊）',category:'周边小吃',cover:null,
excerpt:'阿姨开的煎饼摊，分量足，一定要加肉松。',
content:'<p>后街煎饼阿姨摊，分量足、味道好，一定要记得加肉松（推荐）！</p>',
tags:['煎饼','早餐','后街'],location:'湖南工商大学北校区后街',
recommendedDishes:['煎饼加肉松'],priceRange:'¥5-10',rating:4.5,
pinned:false,sortOrder:12,published:true,createdAt:'2026-08-01T08:00:00Z',updatedAt:'2026-08-08T08:00:00Z'},
{id:'food_013',title:'后街 · 两元面包店',category:'周边小吃',cover:null,
excerpt:'巨好吃！面包多为 3.5/5.5 元，冷萃茉莉推荐，还有糖水铺子。',
content:'<p>后街超高性价比面包店，招牌冷萃茉莉 ¥5.5，味道绝绝子。普通面包 3.5 元起，种类丰富。同家店还有糖水铺子。</p>',
tags:['面包','便宜','后街'],location:'湖南工商大学北校区后街',
recommendedDishes:['冷萃茉莉','3.5元面包套餐'],priceRange:'¥2-8',rating:4.7,
pinned:true,sortOrder:13,published:true,createdAt:'2026-08-01T08:00:00Z',updatedAt:'2026-08-08T08:00:00Z'},
{id:'food_014',title:'后街 · 糖水粥铺',category:'周边小吃',cover:null,
excerpt:'可加小料，中杯 4-7 元，大杯 +2 元。便宜解暑。',
content:'<p>后街糖水粥铺，招牌绿豆沙、薏米水、西米露等，可加芋圆、椰果等小料。</p>',
tags:['糖水','解暑','便宜'],location:'湖南工商大学北校区后街',
recommendedDishes:['绿豆沙','薏米西米露'],priceRange:'¥4-9',rating:4.4,
pinned:false,sortOrder:14,published:true,createdAt:'2026-08-01T08:00:00Z',updatedAt:'2026-08-08T08:00:00Z'},
{id:'food_015',title:'后街右转 · 湘味浓',category:'聚餐餐厅',cover:null,
excerpt:'量大便宜，后街右转即到，馆内还有临榆炸鸡腿和云南米线。',
content:'<p>出后街右转步行 2 分钟，湘味浓饭馆，量大便宜，适合多人聚餐。馆内同层还有临榆炸鸡腿（连锁）和云南米线（老板好，常搞活动送煎蛋饮料，免费加粉）。</p>',
tags:['湘菜','聚餐','后街附近'],location:'湖南工商大学北校区后街右转',
recommendedDishes:['湘味浓招牌菜','云南米线'],priceRange:'¥15-30',rating:4.6,
pinned:true,sortOrder:15,published:true,createdAt:'2026-08-01T08:00:00Z',updatedAt:'2026-08-08T08:00:00Z'},
{id:'food_016',title:'瑞幸咖啡 · 一食堂旁',category:'奶茶咖啡',cover:null,
excerpt:'铭德食堂旁瑞幸，可买美团/饿了么团购。',
content:'<p>一食堂（铭德）旁边有瑞幸咖啡，支持美团/饿了么团购，价格更便宜。</p>',
tags:['咖啡','团购','一食堂'],location:'湖南工商大学北校区·铭德食堂旁',
recommendedDishes:['生椰拿铁','拿铁'],priceRange:'¥12-20',rating:4.3,
pinned:false,sortOrder:16,published:true,createdAt:'2026-08-01T08:00:00Z',updatedAt:'2026-08-08T08:00:00Z'},
{id:'food_017',title:'后街奶茶店群',category:'奶茶咖啡',cover:null,
excerpt:'后街一点点/书亦/蜜雪/沪上阿姨，沪上阿姨和古茗可送上楼。',
content:'<p>后街奶茶聚集地，一点点、书亦烧仙草、蜜雪冰城、沪上阿姨、古茗全都有。沪上阿姨和古茗支持送上楼（不用自己跑下去拿）。</p>',
tags:['奶茶','外卖','后街'],location:'湖南工商大学北校区后街',
recommendedDishes:['沪上阿姨杨枝甘露','古茗杨枝甘露'],priceRange:'¥8-18',rating:4.4,
pinned:false,sortOrder:17,published:true,createdAt:'2026-08-01T08:00:00Z',updatedAt:'2026-08-08T08:00:00Z'},
{id:'food_018',title:'果链水果店',category:'周边小吃',cover:null,
excerpt:'性价比高、新鲜。注意：烧烤旁边那家水果店是坏的，需避雷。',
content:'<p>后街水果店，性价比高、水果新鲜。注意区分：烧烤摊位旁边的那家水果店品质有问题，避雷。</p>',
tags:['水果','后街','注意避雷'],location:'湖南工商大学北校区后街',
recommendedDishes:['当季水果拼盘'],priceRange:'¥5-15',rating:4.1,
pinned:false,sortOrder:18,published:true,createdAt:'2026-08-01T08:00:00Z',updatedAt:'2026-08-08T08:00:00Z'},
{id:'food_019',title:'小碗菜（后街摊）',category:'周边小吃',cover:null,
excerpt:'现炒味道不错，但人很多，建议早点去。',
content:'<p>后街小碗菜摊位，现点现炒，味道不错。缺点是人多，建议避开饭点高峰期。</p>',
tags:['小碗菜','现炒','后街'],location:'湖南工商大学北校区后街',
recommendedDishes:['小碗菜自选'],priceRange:'¥8-15',rating:4.2,
pinned:false,sortOrder:19,published:true,createdAt:'2026-08-01T08:00:00Z',updatedAt:'2026-08-08T08:00:00Z'}
];
